### ISSUE TITLE
I am not able to see part of the screen

### ISSUE THREAD

**Issue by catdisk04** [games50/pong#63]
This the code I am using:
[New Text Document.txt](https://github.com/games50/pong/files/5254020/New.Text.Document.txt)

 a part of my screen is not seen. therefore, I am not able o see the paddles. What is the mistake I am doing? What should I change?

These are my screen dimensions:
![Screenshot (121)](https://user-images.githubusercontent.com/71630786/93743672-10cf8a80-fc0e-11ea-8482-bf08a7fb2c60.png)

**Comment by coltonoscopy** [comment]
@AldisDaniel try embedding the code using "Insert code" instead of attaching a txt file if possible (makes it easier for myself and others), but my instinct is that you should just change the `WINDOW_WIDTH` and `WINDOW_HEIGHT` constants in the code from 1920 and 1080 respectively to 1280 and 720 and that ought to work well!
